Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

user, password: caractere


Inicio

enquanto (user <> "admin") ou (password <> "admin") faca
         escreval("Usuário ou  senha inválidos")
         escreva("Digite o seu usuário: ")
         leia(user)
         escreva("Digite a sua senha: ")
         leia(password)
fimenquanto

escreval("Seja Bem-Vindo ao sistema")


Fimalgoritmo